apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pruebapipe
  generateName: pipeline-sencillo-run-
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  pipelineRef:
    name: pipeline-sencillo
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
            